#!/bin/bash

CHALLENGE4_DIR="./challenge 4"
CHALLENGE1_DIR="./challenge 1"
CSV_FILE="$CHALLENGE4_DIR/challenge-cut/fourchords.csv"
CUT_PROGRAM="$CHALLENGE4_DIR/cut"
WORDCOUNT_PROGRAM="$CHALLENGE1_DIR/word-count"

go build .
cd ..
cd "$CHALLENGE1_DIR"
go build .
cd ..

if [ "$1" == "1" ]; then
    tail -n5 "$CSV_FILE" | "$CUT_PROGRAM" -f="\"1 2\"" -d=,
elif [ "$1" == "2" ]; then
    tail -n5 "$CSV_FILE" | "$CUT_PROGRAM" -d=, -f="\"1 2\"" -
elif [ "$1" == "3" ]; then
    "$CUT_PROGRAM" -f=2 -d=, "$CSV_FILE" | uniq | "$WORDCOUNT_PROGRAM" -l
else
    echo "Please provide argument 1 or 2 to select which command to run"
    exit 1
fi